"""
    The Anonymity package contains methods which can be used to anonymize the attacker. Proxy's are responsible for
    sending the information generated by AttackMethod classes to the intended target.

    I created the proxy classes myself because I wanted to learn how Proxies work. A better alternative for the
    Proxies module is Requests (http://docs.python-requests.org/en/latest/). The proxy module is simpler than Requests
    and requires knowledge on HTTP.
"""